Exclude fields
westonmiller/mongoose-crud pull request #2
Opened 2017-10-16 17:18 UTC by westonmiller

#### What does it do?
adds the ability to define what fields are excluded from objects when returned

#### Any helpful background information?
None

#### New dependencies? What are they used for?
None

#### Definition of Done
- [ ] it works, tests coming soon, probably

#### Obligatory gif
![](https://media.giphy.com/media/abdf0NKI55852/giphy.gif)

2017-10-16 17:58 UTC, ebassity requested changes

2017-10-16 17:58 UTC, somedayrainbows commented on README.md
> +  exludes: ['password'] //array of properies, that won't be returned from the model
Do you mean excludes here? Looks like it could be a typo?

2017-10-17 15:48 UTC, westonmiller commented on README.md
> +  exludes: ['password'] //array of properies, that won't be returned from the model
thanks

2017-10-17 15:55 UTC, ebassity approved these changes

2017-10-17 15:56 UTC, ebassity commented
Looks great! 🎉

2017-10-17 15:56 UTC, merged